spring:
  application:
    name: jp-service-discovery
server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
logging:
  structured:
    format:
      console: logstash
